// <auto-generated />
using System;
using CarRent.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarRent.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20260107213014_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarRent.Models.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("PricePerDay")
                        .HasColumnType("float");

                    b.Property<int>("RentalType")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("CarId");

                    b.ToTable("tblCars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            Brand = "Toyota",
                            Model = "Corolla",
                            PricePerDay = 30.0,
                            RentalType = 0,
                            Year = 2020
                        },
                        new
                        {
                            CarId = 2,
                            Brand = "Hyundai",
                            Model = "Elantra",
                            PricePerDay = 35.0,
                            RentalType = 0,
                            Year = 2021
                        },
                        new
                        {
                            CarId = 3,
                            Brand = "BMW",
                            Model = "X3",
                            PricePerDay = 60.0,
                            RentalType = 1,
                            Year = 2019
                        },
                        new
                        {
                            CarId = 4,
                            Brand = "Mercedes",
                            Model = "C200",
                            PricePerDay = 120.0,
                            RentalType = 2,
                            Year = 2022
                        });
                });

            modelBuilder.Entity("CarRent.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerId");

                    b.ToTable("tblCustomers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            Email = "alice@email.com",
                            FullName = "Alice"
                        },
                        new
                        {
                            CustomerId = 2,
                            Email = "bob@email.com",
                            FullName = "Bob"
                        });
                });

            modelBuilder.Entity("CarRent.Models.CustomerCar", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "CarId");

                    b.HasIndex("CarId");

                    b.ToTable("CustomerCars");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CarId = 1
                        },
                        new
                        {
                            CustomerId = 1,
                            CarId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            CarId = 3
                        });
                });

            modelBuilder.Entity("CarRent.Models.Rental", b =>
                {
                    b.Property<int>("RentalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentalId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.HasKey("RentalId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("tblRentals");
                });

            modelBuilder.Entity("CarRent.Models.CustomerCar", b =>
                {
                    b.HasOne("CarRent.Models.Car", "Car")
                        .WithMany("CustomerCars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRent.Models.Customer", "Customer")
                        .WithMany("CustomerCars")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarRent.Models.Rental", b =>
                {
                    b.HasOne("CarRent.Models.Car", "Car")
                        .WithMany("Rentals")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarRent.Models.Customer", "Customer")
                        .WithMany("Rentals")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarRent.Models.Car", b =>
                {
                    b.Navigation("CustomerCars");

                    b.Navigation("Rentals");
                });

            modelBuilder.Entity("CarRent.Models.Customer", b =>
                {
                    b.Navigation("CustomerCars");

                    b.Navigation("Rentals");
                });
#pragma warning restore 612, 618
        }
    }
}
